[package]
name = "macros"
authors.workspace = true
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.85"
quote = "1.0.36"
syn = {version = "2.0.66", features = ["full", "extra-traits", "visit-mut", "visit"]}
macro-cores.workspace = true
